// RUDE - RAGE <-> Unreal Development Environment
// The RUDE CLI. Argument handling only - the reflective call path lives in RudeInvoke, shared with
// the Slate panel so the two surfaces cannot diverge.
#include "RudeCommandlet.h"

#include "RudeInvoke.h"
#include "UObject/UnrealType.h"

DEFINE_LOG_CATEGORY_STATIC(LogRudeCLI, Log, All);

namespace
{
	// Output goes through the log, which is what a terminal or CI actually reads. Display
	// verbosity survives -stdout without needing -verbose.
	void Say(const FString& Line)
	{
		UE_LOG(LogRudeCLI, Display, TEXT("%s"), *Line);
	}
}

URudeCommandlet::URudeCommandlet()
{
	IsClient = false;
	IsServer = false;
	IsEditor = true;
	LogToConsole = true;
	ShowErrorCount = false;
}

int32 URudeCommandlet::Main(const FString& Params)
{
	TArray<FString> Tokens;
	TArray<FString> Switches;
	TMap<FString, FString> Pairs;
	UCommandlet::ParseCommandLine(*Params, Tokens, Switches, Pairs);

	const TArray<UFunction*> Tools = FRudeInvoke::CollectTools();
	const FString* ToolName = Pairs.Find(TEXT("tool"));

	if (Switches.Contains(TEXT("list")) || Switches.Contains(TEXT("help")) || !ToolName)
	{
		Say(TEXT(""));
		Say(FString::Printf(TEXT("RUDE CLI - %d tools (generated by reflection from URudeToolset, "
			"so this list is never stale)"), Tools.Num()));
		Say(TEXT(""));
		for (const UFunction* Fn : Tools)
		{
			Say(FString::Printf(TEXT("  %s(%s)"), *Fn->GetName(),
				*FString::Join(FRudeInvoke::ParamNames(Fn), TEXT(", "))));
		}
		Say(TEXT(""));
		Say(TEXT("  -tool=<Name> then one argument per parameter, positionally:"));
		Say(TEXT("     -run=/Script/RudeEditor.RudeCommandlet -tool=ImportYdr \"C:/x/p.ydr.xml\" "
			"/Game/RUDE/Props"));
		Say(TEXT("  or by name, which is order-independent and clearer in scripts:"));
		Say(TEXT("     ... -tool=ImportYdr -XmlPath=\"C:/x/p.ydr.xml\" -DestFolder=/Game/RUDE/Props"));
		Say(TEXT("  Omitted parameters pass as empty strings, matching the MCP behaviour."));
		Say(TEXT("  Each tool prints the JSON the agent surface returns; the exit code is that "
			"tool's own verdict (non-zero only when it reports ok:false)."));
		Say(TEXT("  NOTE: use the FULLY-QUALIFIED -run=/Script/RudeEditor.RudeCommandlet, and pass "
			"it as an argument ARRAY - a shell that splits it on the '.' makes UE die in "
			"AddModule() on an empty module name."));
		Say(TEXT(""));
		return 0;
	}

	UFunction* Fn = FRudeInvoke::FindTool(*ToolName);
	if (!Fn)
	{
		Say(FString::Printf(TEXT("unknown tool '%s'. -list shows the %d that exist."),
			**ToolName, Tools.Num()));
		return 1;
	}

	// Positional arguments are the leftover tokens; -Name=value wins over position when both are
	// given, so a script can be explicit without depending on argument order.
	const TArray<FString> Names = FRudeInvoke::ParamNames(Fn);
	TArray<FString> Values;
	Values.Reserve(Names.Num());
	int32 PositionalIdx = 0;
	for (const FString& Name : Names)
	{
		if (const FString* Named = Pairs.Find(Name))
		{
			Values.Add(*Named);
			continue;
		}
		Values.Add(Tokens.IsValidIndex(PositionalIdx) ? Tokens[PositionalIdx] : FString());
		++PositionalIdx;
	}

	FString Result;
	FString Error;
	if (!FRudeInvoke::Call(Fn, Values, Result, Error))
	{
		Say(Error);
		return 1;
	}
	Say(Result);
	return FRudeInvoke::ReportedFailure(Result) ? 1 : 0;
}
