// RUDE - RAGE <-> Unreal Development Environment
// The RUDE CLI. See RudeCommandlet.h for why this dispatches reflectively.
#include "RudeCommandlet.h"

#include "RudeToolset.h"
#include "UObject/UnrealType.h"

DEFINE_LOG_CATEGORY_STATIC(LogRudeCLI, Log, All);

namespace
{
	// Output goes to stdout via the log, which is what a terminal/CI actually reads. Display
	// verbosity survives -stdout without needing -verbose.
	void Say(const FString& Line)
	{
		UE_LOG(LogRudeCLI, Display, TEXT("%s"), *Line);
	}

	bool IsAgentCallable(const UFunction* Fn)
	{
#if WITH_EDITORONLY_DATA
		// The same marker the MCP layer keys off, so the two surfaces expose the same set.
		return Fn->HasMetaData(TEXT("AICallable"));
#else
		return true;
#endif
	}

	// Parameter names in declaration order, excluding the return value.
	TArray<FString> ParamNames(const UFunction* Fn)
	{
		TArray<FString> Out;
		for (TFieldIterator<FProperty> It(Fn); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
		{
			if (It->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				continue;
			}
			Out.Add(It->GetName());
		}
		return Out;
	}

	// Every tool takes only FStrings and returns an FString. A tool that ever stops doing so must
	// be reported rather than silently invoked with zeroed arguments.
	bool IsAllStrings(const UFunction* Fn, FString& OutWhy)
	{
		bool bFoundReturn = false;
		for (TFieldIterator<FProperty> It(Fn); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
		{
			if (!CastField<FStrProperty>(*It))
			{
				OutWhy = FString::Printf(TEXT("parameter '%s' is %s, not FString"),
					*It->GetName(), *It->GetClass()->GetName());
				return false;
			}
			if (It->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				bFoundReturn = true;
			}
		}
		if (!bFoundReturn)
		{
			OutWhy = TEXT("no FString return value");
			return false;
		}
		return true;
	}

	TArray<UFunction*> CollectTools()
	{
		TArray<UFunction*> Tools;
		for (TFieldIterator<UFunction> It(URudeToolset::StaticClass(),
			EFieldIteratorFlags::ExcludeSuper); It; ++It)
		{
			if (IsAgentCallable(*It))
			{
				Tools.Add(*It);
			}
		}
		Tools.Sort([](const UFunction& A, const UFunction& B)
		{
			return A.GetName() < B.GetName();
		});
		return Tools;
	}
}

URudeCommandlet::URudeCommandlet()
{
	IsClient = false;
	IsServer = false;
	IsEditor = true;
	LogToConsole = true;
	ShowErrorCount = false;
}

int32 URudeCommandlet::Main(const FString& Params)
{
	TArray<FString> Tokens;
	TArray<FString> Switches;
	TMap<FString, FString> Pairs;
	UCommandlet::ParseCommandLine(*Params, Tokens, Switches, Pairs);

	const TArray<UFunction*> Tools = CollectTools();

	const FString* ToolName = Pairs.Find(TEXT("tool"));
	const bool bWantList = Switches.Contains(TEXT("list")) || Switches.Contains(TEXT("help"))
		|| !ToolName;

	if (bWantList)
	{
		Say(TEXT(""));
		Say(FString::Printf(TEXT("RUDE CLI - %d tools (generated by reflection from URudeToolset, "
			"so this list is never stale)"), Tools.Num()));
		Say(TEXT(""));
		for (const UFunction* Fn : Tools)
		{
			const TArray<FString> Names = ParamNames(Fn);
			Say(FString::Printf(TEXT("  %s(%s)"), *Fn->GetName(), *FString::Join(Names, TEXT(", "))));
		}
		Say(TEXT(""));
		Say(TEXT("  -tool=<Name> then one argument per parameter, positionally:"));
		Say(TEXT("     -run=RudeCommandlet -tool=ImportYdr \"C:/x/prop.ydr.xml\" /Game/RUDE/Props"));
		Say(TEXT("  or by name, which is order-independent and clearer in scripts:"));
		Say(TEXT("     -run=RudeCommandlet -tool=ImportYdr -XmlPath=\"C:/x/prop.ydr.xml\" "
			"-DestFolder=/Game/RUDE/Props"));
		Say(TEXT("  Omitted parameters pass as empty strings, matching the MCP behaviour."));
		Say(TEXT("  Each tool prints the same JSON the agent surface returns; exit code is 0 only "
			"when that JSON reports ok:true."));
		Say(TEXT(""));
		return 0;
	}

	UFunction* Fn = nullptr;
	for (UFunction* Candidate : Tools)
	{
		if (Candidate->GetName().Equals(*ToolName, ESearchCase::IgnoreCase))
		{
			Fn = Candidate;
			break;
		}
	}
	if (!Fn)
	{
		Say(FString::Printf(TEXT("unknown tool '%s'. -list shows the %d that exist."),
			**ToolName, Tools.Num()));
		return 1;
	}

	FString Why;
	if (!IsAllStrings(Fn, Why))
	{
		// Refusing beats invoking with a zeroed argument buffer, which would look like a run.
		Say(FString::Printf(TEXT("tool '%s' cannot be driven from the CLI: %s. The CLI marshals "
			"FString arguments only."), *Fn->GetName(), *Why));
		return 1;
	}

	// Positional arguments are the leftover tokens; -Name=value wins over position when both are
	// given, so a script can be explicit without rewriting argument order.
	const TArray<FString> Names = ParamNames(Fn);
	TArray<FString> Values;
	Values.Reserve(Names.Num());
	int32 PositionalIdx = 0;
	for (const FString& Name : Names)
	{
		if (const FString* Named = Pairs.Find(Name))
		{
			Values.Add(*Named);
			continue;
		}
		Values.Add(Tokens.IsValidIndex(PositionalIdx) ? Tokens[PositionalIdx] : FString());
		++PositionalIdx;
	}

	// Marshal into a UFunction parameter frame. Every value must be constructed before use and
	// destroyed after, or FString parameters leak / free garbage.
	TArray<uint8> Frame;
	Frame.SetNumZeroed(Fn->ParmsSize);
	for (TFieldIterator<FProperty> It(Fn); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
	{
		It->InitializeValue_InContainer(Frame.GetData());
	}

	FStrProperty* ReturnProp = nullptr;
	int32 ValueIdx = 0;
	for (TFieldIterator<FProperty> It(Fn); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
	{
		FStrProperty* Str = CastField<FStrProperty>(*It);
		if (It->HasAnyPropertyFlags(CPF_ReturnParm))
		{
			ReturnProp = Str;
			continue;
		}
		if (Str && Values.IsValidIndex(ValueIdx))
		{
			Str->SetPropertyValue_InContainer(Frame.GetData(), Values[ValueIdx]);
		}
		++ValueIdx;
	}

	// The tools are static UFUNCTIONs; UE routes those through the class default object.
	UObject* Target = URudeToolset::StaticClass()->GetDefaultObject();
	Target->ProcessEvent(Fn, Frame.GetData());

	FString Result;
	if (ReturnProp)
	{
		Result = ReturnProp->GetPropertyValue_InContainer(Frame.GetData());
	}

	for (TFieldIterator<FProperty> It(Fn); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
	{
		It->DestroyValue_InContainer(Frame.GetData());
	}

	Say(Result);

	// Exit code from the tool's OWN verdict, not merely from "it ran" - a CI step that only checks
	// the process code would otherwise treat {"ok":false} as success.
	//
	// ⚠ POLARITY MATTERS: fail only when a tool SAYS it failed. Requiring "ok":true instead made
	// `Ping` - which returns a plain sentence, not JSON - exit 1 on a completely successful run.
	// Not every tool returns a JSON envelope, so absence of one is not failure.
	const bool bFailed = Result.Contains(TEXT("\"ok\":false"))
		|| Result.Contains(TEXT("\"ok\": false"));
	return bFailed ? 1 : 0;
}
